---
title: "IDZ_5"
author: "Nikita"
date: "22.04.17"
output:
  html_document:
    keep_md: yes
    output: null
    toc_float: yes0
  pdf_document:
    keep_tex: yes
    toc: yes
  word_document: default
  github_document: rmarkdown::github_document
params:
  bibliography: bibl.bib
  urlcolor: blue
---

```{r setup, include=FALSE}
library(dplyr)
library(tidyr)
library(xtable)
library(ggvis)
library(ggplot2)
library(kolmim)
options(scipen = 0, digits = 3)
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE,fig.path = "README_figs/README-")
```

```{r}
n<-1000
alpha1<-0.2
alpha2<-0.1
alpha3<-0.05
alpha4<-0.01
def_a<-5
def_disp<-1

# ГЕНЕРАЦИЯ ВЫБОРКИ
norm<-rnorm(n,def_a,def_disp)
norm<-sort(norm)

# ФУНКЦИЯ ПОРОГОВОГО ЗНАЧЕНИЯ КРИТЕРИЯ (КВАНТИЛИ)
quantile_kolm=function(alpha,n) {
  return (sqrt(-1/2*log(alpha/2))/sqrt(n))
}

# ФУНКЦИЯ РАСПРЕДЕЛЕНИЯ В ТОЧКЕ t
F=function(t){
  return (pnorm(t,def_a,def_disp))             # ЗДЕСЬ ЗАДАЕТСЯ (EPS)
}

# ЭМПИРИЧЕСКАЯ ФУНКЦИЯ РАСПРЕДЕЛЕНИЯ
Fn<-ecdf(norm)

l1<-norm[1:(n-1)]
l2<-norm[2:n]
m<-min(abs(l1-l2))
eps<-0.1*m


# СТАТИСТИКА МАКСИМАЛЬНОГО ОТКЛОНЕНИЯ
Dn<-0
for(y in norm) {
  d1<-abs(Fn(y) - F(y))
  d2<-abs(Fn(y-eps) - F(y))
  d<-max(d1,d2)
  if(d>Dn) {
    Dn<-d
  }
}

q_kolm<-numeric(4)
q_kolm[1]<-quantile_kolm(alpha1,n)
q_kolm[2]<-quantile_kolm(alpha2,n)
q_kolm[3]<-quantile_kolm(alpha3,n)
q_kolm[4]<-quantile_kolm(alpha4,n)


# ЕСЛИ СТАТИСТИКА Dn МЕНЬШЕ ПОРОГОВОГО ЗНАЧЕНИЯ ПРИ ДАННЫХ ПАРАМЕТРАХ, ПРИНИМАЕТСЯ Н_0. ИНАЧЕ Н_1

for(i in 1:4) {
  if(Dn < q_kolm[i]) {
    print("H_0")
  } else {
    print("H_1")
  }
}

my_pvalue_kolm<-1-pkolm(Dn,n)

tmp_kolm<-ks.test(norm, "pnorm", def_a, def_disp)        # ЗДЕСЬ ЗАДАЁТСЯ (EPS)
pvalue_kolm<-tmp_kolm$p.value
statistics_kolm<-tmp_kolm$statistic

###########################################( ХИ КВАДРАТ )###################################################

# КВАНТИЛИ
q_chisq<-numeric(4)
q_chisq[1]<-qchisq(1-alpha1/2,n-1)
q_chisq[2]<-qchisq(1-alpha2/2,n-1)
q_chisq[3]<-qchisq(1-alpha3/2,n-1)
q_chisq[4]<-qchisq(1-alpha4/2,n-1)

# РАЗБИЕНИЕ НА ПРОМЕЖУТКИ
steps<-numeric(9)
for(i in 1:9) {
  steps[i]<-qnorm(i/10,def_a,def_disp)
}

# ОЖИДАЕМОЕ И НАБЛЮДАЕМОЕ ПОПАДАНИЕ В ПРОМЕЖУТКИ
ojidaem=n/10
nb=hist(norm,breaks=c(min(norm),steps,max(norm)), plot=FALSE)
nabludaem=nb$counts

# CТАТИСТИКА
Hi=sum(((nabludaem-ojidaem)^2)/ojidaem)

for (i in 1:4) {
  if (Hi <= q_chisq[i]) {
    print("H_0")
  } else {
    print("H_1")
  }
}

#PVALUE AND STATISTIC
prob=rep(1/10,each=10)
t_chisq=chisq.test(nabludaem,p=prob)
pvalue_chisq=t_chisq$p.value
statistics_chisq=t_chisq$statistic


###################################################################################################

pvalues<-numeric(1000)
pvalues_chisq<-vector()
def_a<-5
def_disp<-1

for(i in 1:1000) {
  nm<-rnorm(1000,def_a,def_disp)
  nm<-sort(nm)
  tmp<-ks.test(nm,"pnorm",def_a+0.1,def_disp)            # ЗДЕСЬ ЗАДАЁТСЯ (EPS)
  pvalues[i]<-tmp$p.value
}

# ПОСТРОЕНИЕ ГИСТОГРАММЫ ДЛЯ ПУНКТА 3 ЗАДАНИЯ 1
h=hist(pvalues, breaks=30, col="green",freq=FALSE)
dens<-dunif(sort(pvalues)); lines(sort(pvalues),dens,col="blue",lwd=2)

# ХИ-КВАДРАТ
for(i in 1:1000) {
  rl<-rnorm(1000,def_a, def_disp)
  rl<-sort(rl)
  prob=rep(1/10,each=10)
  steps<-numeric(9)
  for(i in 1:9) {
    steps[i]<-qnorm(i/10,def_a, def_disp)
  }
  nb=hist(rl,breaks=c(min(rl),steps,max(rl)), plot=FALSE)
  nabludaem=nb$counts
  t_chisq=chisq.test(nabludaem,p=prob)
  pvalues_chisq<-append(pvalues_chisq,t_chisq$p.value)
  #pvalues_chisq[i]<-t_chisq$p.value
}
h_chisq=hist(pvalues_chisq, breaks=30, col="green", freq=FALSE)
```



```{r}
n<-1000
alpha1<-0.2
alpha2<-0.1
alpha3<-0.05
alpha4<-0.01
def_p<-2
def_q<-3

#ГЕНЕРАЦИЯ ВЫБОРКИ
beta<-rbeta(n,def_p,def_q)
beta<-sort(beta)

# ( КОЛМОГОРОВ ) ФУНКЦИЯ ПОРОГОВОГО ЗНАЧЕНИЯ КРИТЕРИЯ (КВАНТИЛИ)
quantile_kolm=function(alpha,n) {
  return (sqrt(-1/2*log(alpha/2))/sqrt(n))
}

# ( КОЛМОГОРОВ ) ФУНКЦИЯ РАСПРЕДЕЛЕНИЯ В ТОЧКЕ t
F=function(t){
  return (pbeta(t,def_p+0.001,def_q))             # ЗДЕСЬ ЗАДАЕТСЯ (EPS)
}

# ( КОЛМОГОРОВ ) ЭМПИРИЧЕСКАЯ ФУНКЦИЯ РАСПРЕДЕЛЕНИЯ
Fn<-ecdf(beta)

l1<-beta[1:(n-1)]
l2<-beta[2:n]
m<-min(abs(l1-l2))
eps<-0.1*m


# ( КОЛМОГОРОВ ) СТАТИСТИКА МАКСИМАЛЬНОГО ОТКЛОНЕНИЯ
Dn<-0
for(y in beta) {
  d1<-abs(Fn(y) - F(y))
  d2<-abs(Fn(y-eps) - F(y))
  d<-max(d1,d2)
  if(d>Dn) {
    Dn<-d
  }
}

q_kolm<-numeric(4)
q_kolm[1]<-quantile_kolm(alpha1,n)
q_kolm[2]<-quantile_kolm(alpha2,n)
q_kolm[3]<-quantile_kolm(alpha3,n)
q_kolm[4]<-quantile_kolm(alpha4,n)


# ( КОЛМОГОРОВ ) ЕСЛИ СТАТИСТИКА Dn МЕНЬШЕ ПОРОГОВОГО ЗНАЧЕНИЯ ПРИ ДАННЫХ ПАРАМЕТРАХ, ПРИНИМАЕТСЯ Н_0. ИНАЧЕ Н_1

for(i in 1:4) {
  if(Dn < q_kolm[i]) {
    print("H_0")
  } else {
    print("H_1")
  }
}

my_pvalue_kolm<-1-pkolm(Dn,n)
tmp_kolm<-ks.test(beta, "pbeta", def_p+0.001, def_q)        # ЗДЕСЬ ЗАДАЁТСЯ (EPS)
pvalue_kolm<-tmp_kolm$p.value
statistics_kolm<-tmp_kolm$statistic

###########################################( ХИ КВАДРАТ )###################################################

# КВАНТИЛИ
q_chisq<-numeric(4)
q_chisq[1]<-qchisq(1-alpha1/2,n-1)
q_chisq[2]<-qchisq(1-alpha2/2,n-1)
q_chisq[3]<-qchisq(1-alpha3/2,n-1)
q_chisq[4]<-qchisq(1-alpha4/2,n-1)

# РАЗБИЕНИЕ НА ПРОМЕЖУТКИ
steps<-numeric(9)
for(i in 1:9) {
  steps[i]<-qbeta(i/10,def_p,def_q)
}

# ОЖИДАЕМОЕ И НАБЛЮДАЕМОЕ ПОПАДАНИЕ В ПРОМЕЖУТКИ
ojidaem=n/10
nb=hist(beta,breaks=c(min(beta),steps,max(beta)), plot=FALSE)
nabludaem=nb$counts

# CТАТИСТИКА
Hi=sum(((nabludaem-ojidaem)^2)/ojidaem)

for (i in 1:4) {
  if (Hi <= q_chisq[i]) {
    print("H_0")
  } else {
    print("H_1")
  }
}

#PVALUE AND STATISTIC
prob=rep(1/10,each=10)
t_chisq=chisq.test(nabludaem,p=prob)
pvalue_chisq=t_chisq$p.value
statistics_chisq=t_chisq$statistic


############################################################################################################
pvalues_chisq<-vector()
pvalues<-numeric(1000)
def_p<-2
def_q<-3

for(i in 1:1000) {
  bt<-rbeta(1000,def_p,def_q)
  bt<-sort(bt)
  tmp<-ks.test(bt,"pbeta",def_p,def_q)            # ЗДЕСЬ ЗАДАЁТСЯ (EPS)
  pvalues[i]<-tmp$p.value
}

# ПОСТРОЕНИЕ ГИСТОГРАММЫ ДЛЯ ПУНКТА 3 ЗАДАНИЯ 1
h=hist(pvalues, breaks=30, col="green",freq=FALSE)
dens<-dunif(sort(pvalues)); lines(sort(pvalues),dens,col="blue",lwd=2)

# ХИ-КВАДРАТ
for(i in 1:1000) {
  rl<-rbeta(1000,def_p, def_q)
  rl<-sort(rl)
  prob=rep(1/10,each=10)
  steps<-numeric(9)
  for(i in 1:9) {
    steps[i]<-qbeta(i/10,def_p, def_q)
  }
  nb=hist(rl,breaks=c(min(rl),steps,max(rl)), plot=FALSE)
  nabludaem=nb$counts
  t_chisq=chisq.test(nabludaem,p=prob)
  pvalues_chisq<-append(pvalues_chisq,t_chisq$p.value)
  #pvalues_chisq[i]<-t_chisq$p.value
}
h_chisq=hist(pvalues_chisq, breaks=30, col="green", freq=FALSE)

```